create table CHINHANH(
MACN nChar(10) NOT NULL,
ChiNhanh nvarchar(100) NOT NULL UNIQUE,
DIACHI nvarchar(100),
SoDT nvarchar(100),
primary key (MACN)
);


create table NHANVIEN(
MANV int NOT NULL,
HO nvarchar(40) ,
TEN nvarchar(100),
DIACHI nvarchar(100),
NGAYSINH datetime,
LUONG float CHECK (LUONG >= 4000000),
primary key (MANV),
MACN nchar(10)
);

ALTER TABLE NHANVIEN 
   ADD FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN);


create table KHO(
MAKHO nchar(6) NOT NULL,
TENKHO nvarchar(30) NOT NULL UNIQUE,
DIACHI nvarchar(100),
MACN nchar(10),
primary key(MAKHO)
);

ALTER TABLE KHO 
   ADD FOREIGN KEY (MACN) REFERENCES ChiNhanh(MACN);

create table VATTU(
MAVT nchar(4)	NOT NULL,
TENVT nvarchar(30) NOT NULL UNIQUE,
DVT nvarchar(15),
SOLUONGTON int check (SOLUONGTON >=0),
primary key(MAVT)
);

create table DATHANG(
MasoDDH nchar(8) NOT NULL,
NGAY date ,
NhaCC nvarchar(100) NOT NULL,
MANV int ,
MAKHO nchar(6),
primary key(MasoDDH)
);

ALTER TABLE DATHANG 
	ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE DATHANG 
	ADD FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO);

ALTER TABLE DATHANG 
	ADD CONSTRAINT DATHANG_NGAY_D default getdate() for NGAY;

create table CTDDH(
MasoDDH nchar(8),
MAVT nchar(4),
SOLUONG int check (SOLUONG > 0),
DONGIA float check (DONGIA > 0),
primary key(MasoDDH,MAVT)
);

ALTER TABLE CTDDH 
   ADD FOREIGN KEY (MasoDDH) REFERENCES DATHANG(MasoDDH);

ALTER TABLE CTDDH 
   ADD FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT);

create table PHIEUNHAP(
MAPN nchar(8) NOT NULL,
NGAY date ,
MasoDDH nchar(8) NOT NULL UNIQUE,
MANV int ,
MAKHO nchar(6), 
primary key(MAPN)
);

ALTER TABLE PHIEUNHAP 
	ADD FOREIGN KEY (MasoDDH) REFERENCES DATHANG(MasoDDH);

ALTER TABLE PHIEUNHAP 
	ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE PHIEUNHAP 
	ADD FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO);

ALTER TABLE PHIEUNHAP 
	ADD CONSTRAINT PHIEUNHAP_NGAY_D default getdate() for NGAY;

create table CTPN(
MAPN nchar(8),
MAVT nchar(4),
SOLUONG int check (SOLUONG > 0),
DONGIA float check (DONGIA >= 0),
primary key(MAPN,MAVT)
);

ALTER TABLE CTPN 
   ADD FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN);

ALTER TABLE CTPN 
   ADD FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT);

create table PHIEUXUAT(
MAPX nchar(8) NOT NULL,
NGAY date ,
HOTENKH nvarchar(100) NOT NULL,
MANV int ,
MAKHO nchar(6),
primary key(MAPX)
);

ALTER TABLE PHIEUXUAT 
   ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE PHIEUXUAT 
   ADD FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO);

ALTER TABLE PHIEUXUAT 
	ADD CONSTRAINT PHIEUXUAT_NGAY_D default getdate() for NGAY;

create table CTPX(
MAPX nchar(8),
MAVT nchar(4),
SOLUONG int check (SOLUONG > 0 ),
DONGIA float check (DONGIA >=0 ),
primary key(MAPX,MAVT)
);

ALTER TABLE CTPX 
   ADD FOREIGN KEY (MAPX) REFERENCES PHIEUXUAT(MAPX);

ALTER TABLE CTPX 
   ADD FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT);
