CREATE PROC [dbo].[SP_HoatDongNV]
@MANV int,
@STARTTIME DATE,
@LASTTIME DATE
AS
BEGIN
	DECLARE @DAT_NHAP_XUAT TABLE(MADNX NCHAR(8), NGAY DATE, MANV INT, MAKHO NCHAR(4), LOAI NCHAR(3), NHACC NVARCHAR(100), HOTENKH NVARCHAR(100))
	DECLARE @CTDAT_NHAP_XUAT TABLE(MADNX NCHAR(8), MAVT NCHAR(4), SOLUONG INT, DONGIA FLOAT, THANHTIEN FLOAT)
	BEGIN
		INSERT INTO @DAT_NHAP_XUAT(MADNX, NGAY, MANV, MAKHO, LOAI, NHACC)
		SELECT MasoDDH, NGAY, MANV, MAKHO, LOAI=N'DH', NhaCC FROM dbo.DATHANG 
		INSERT INTO @DAT_NHAP_XUAT(MADNX, NGAY, MANV, MAKHO, LOAI)
		SELECT MAPN, NGAY, MANV, MAKHO, LOAI=N'PN' FROM dbo.PHIEUNHAP
		INSERT INTO @DAT_NHAP_XUAT(MADNX, NGAY, MANV, MAKHO, LOAI, HOTENKH)
		SELECT MAPX, NGAY, MANV, MAKHO, LOAI=N'PX', HOTENKH FROM dbo.PHIEUXUAT
	END
	BEGIN
		INSERT INTO @CTDAT_NHAP_XUAT(MADNX, MAVT, SOLUONG, DONGIA, THANHTIEN)
		SELECT MasoDDH, MAVT, SOLUONG, DONGIA, (SOLUONG*DONGIA) FROM dbo.CTDDH 
		INSERT INTO @CTDAT_NHAP_XUAT(MADNX, MAVT, SOLUONG, DONGIA, THANHTIEN)
		SELECT MAPN, MAVT, SOLUONG, DONGIA, (SOLUONG*DONGIA) FROM dbo.CTPN
		INSERT INTO @CTDAT_NHAP_XUAT(MADNX, MAVT, SOLUONG, DONGIA, THANHTIEN)
		SELECT MAPX, MAVT, SOLUONG, DONGIA, (SOLUONG*DONGIA) FROM dbo.CTPX
	END
	BEGIN
		SELECT NV.MACN, NV.MANV, NV.HO + ' ' + NV.TEN AS HOTEN, NV.NGAYSINH, NV.DIACHI, NV.LUONG, DNX.NGAY, DNX.MADNX, DNX.HOTENKH, 
		VT.TENVT, KHO.TENKHO, CT_DNX.SOLUONG, CT_DNX.DONGIA, CT_DNX.THANHTIEN, DNX.LOAI, DNX.NHACC, DNX.HOTENKH 
		FROM (SELECT MADNX, NGAY, MANV, MAKHO, LOAI, NHACC, HOTENKH FROM @DAT_NHAP_XUAT WHERE MANV = @MANV AND NGAY BETWEEN @STARTTIME AND @LASTTIME) AS DNX,
			( SELECT MADNX, MAVT, SOLUONG, DONGIA, THANHTIEN FROM @CTDAT_NHAP_XUAT) AS CT_DNX,
			(SELECT MANV, HO, TEN, NGAYSINH, DIACHI, LUONG, MACN FROM dbo.NHANVIEN) AS NV,
			(SELECT MAKHO, TENKHO FROM dbo.KHO) AS KHO,
			(SELECT MAVT, TENVT, DVT, SOLUONGTON FROM dbo.VATTU) AS VT
			WHERE DNX.MADNX = CT_DNX.MADNX AND DNX.MANV = NV.MANV AND CT_DNX.MAVT = VT.MAVT AND DNX.MAKHO = KHO.MAKHO
	END
END