USE [QLVT]
GO
/****** Object:  StoredProcedure [dbo].[SP_SLTG_Nhap_Xuat]    Script Date: 30/11/2017 12:17:02 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_In_SLTG_Nhap_Xuat]
@ROLE NCHAR(10),
@STARTTIME DATE,
@LASTTIME DATE
AS
BEGIN
	DECLARE @TABLE_NHAP_XUAT TABLE(MANX NCHAR(8), NGAY DATE, MANV INT, MAKHO NCHAR(4), LOAI NCHAR(3))
	DECLARE @TABLE_CT_NHAP_XUAT TABLE(MANX NCHAR(8), MAVT NCHAR(4), SOLUONG INT, DONGIA FLOAT, THANHTIEN FLOAT)
	IF(@ROLE = 'CHINHANH')
	BEGIN
		BEGIN
			INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MANV, MAKHO, LOAI )
			SELECT MAPN, NGAY, MANV, MAKHO, LOAI=N'PN' FROM dbo.PHIEUNHAP
			INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MANV, MAKHO, LOAI )
			SELECT MAPX, NGAY, MANV, MAKHO, LOAI=N'PX' FROM dbo.PHIEUXUAT
		END
		BEGIN
			INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
			SELECT MAPN, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM dbo.CTPN
			INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
			SELECT MAPX, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM dbo.CTPX
		END
	END
	IF(@ROLE = 'CONGTY')
	BEGIN
		BEGIN
			INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MANV, MAKHO, LOAI )
			SELECT MAPN, NGAY, MANV, MAKHO, LOAI=N'PN' FROM dbo.PHIEUNHAP
			INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MANV, MAKHO, LOAI )
			SELECT MAPX, NGAY, MANV, MAKHO, LOAI=N'PN' FROM dbo.PHIEUXUAT
			INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MANV, MAKHO, LOAI )
			SELECT MAPN, NGAY, MANV, MAKHO, LOAI=N'PN' FROM LINK1.QLVT.dbo.PHIEUNHAP
			INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MANV, MAKHO, LOAI )
			SELECT MAPX, NGAY, MANV, MAKHO, LOAI=N'PN' FROM LINK1.QLVT.dbo.PHIEUXUAT
		END
		BEGIN
			INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
			SELECT MAPN, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM dbo.CTPN
			INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
			SELECT MAPX, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM dbo.CTPX
			INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
			SELECT MAPN, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM LINK1.QLVT.dbo.CTPN
			INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
			SELECT MAPX, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM LINK1.QLVT.dbo.CTPX
		END
	END
	BEGIN
		SELECT NX.THANG, VT.TENVT, NX.LOAI, SUM(CT_NX.SOLUONG) AS SOLUONG, SUM(CT_NX.DONGIA) AS DONGIA, SUM(CT_NX.THANHTIEN) AS THANHTIEN
		FROM (SELECT MANX, CAST(MONTH(NGAY) AS VARCHAR(10))+'/'+CAST(YEAR(NGAY) AS VARCHAR(10)) AS THANG, LOAI FROM @TABLE_NHAP_XUAT WHERE NGAY BETWEEN @STARTTIME AND @LASTTIME) AS NX,
			(SELECT MANX, MAVT, SOLUONG, DONGIA, THANHTIEN FROM @TABLE_CT_NHAP_XUAT) AS CT_NX,
			(SELECT MAVT, TENVT FROM dbo.VATTU) AS VT
		WHERE NX.MANX = CT_NX.MANX AND CT_NX.MAVT = VT.MAVT
		GROUP BY NX.THANG, VT.TENVT, NX.LOAI
	END
END