CREATE PROC [dbo].[SP_In_Tong_SLTG_PhieuNhap]
@YEAR INT
AS
BEGIN
	BEGIN
		SELECT MONTH(dbo.PHIEUNHAP.NGAY) AS THANG, COUNT(dbo.PHIEUNHAP.MAPN) AS SOLUONG, SUM(dbo.CTPN.SOLUONG*dbo.CTPN.DONGIA) AS TRIGIA
		FROM dbo.PHIEUNHAP, dbo.CTPN
		WHERE dbo.PHIEUNHAP.MAPN = dbo.CTPN.MAPN AND YEAR(NGAY) = @YEAR
		GROUP BY MONTH(NGAY)
	END
END