CREATE PROC [dbo].[SP_In_SLTG_Nhap_Xuat_QUANTRI]
@STARTTIME DATE,
@LASTTIME DATE
AS
BEGIN
	DECLARE @TABLE_NHAP_XUAT TABLE(MANX NCHAR(8), NGAY DATE, MADDH NCHAR(4), MANV INT, LOAI NCHAR(3))
	DECLARE @TABLE_CT_NHAP_XUAT TABLE(MANX NCHAR(8), MAVT NCHAR(8), SOLUONG INT, DONGIA FLOAT, THANHTIEN FLOAT)
	BEGIN
		INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MADDH, MANV, LOAI )
		SELECT MAPN, NGAY, MADDH, MANV, LOAI=N'PN' FROM dbo.PHIEUNHAP
		INSERT INTO @TABLE_NHAP_XUAT( MANX, NGAY, MADDH, MANV, LOAI )
		SELECT MAPX, NGAY, MADDH, MANV, LOAI=N'PX' FROM dbo.PHIEUXUAT
	END
	BEGIN
		INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
		SELECT MAPN, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM dbo.CTPN
		INSERT INTO @TABLE_CT_NHAP_XUAT( MANX, MAVT, SOLUONG, DONGIA, THANHTIEN)
		SELECT MAPX, MAVT, SOLUONG, DONGIA, SOLUONG*DONGIA FROM dbo.CTPX
	END
	BEGIN
		SELECT NX.THANG, VT.TENVT, NX.LOAI, SUM(CT_NX.SOLUONG) AS SOLUONG, SUM(CT_NX.DONGIA) AS DONGIA, SUM(CT_NX.THANHTIEN) AS THANHTIEN
		FROM (SELECT MANX, CAST(MONTH(NGAY) AS VARCHAR(10))+'/'+CAST(YEAR(NGAY) AS VARCHAR(10)) AS THANG, LOAI FROM @TABLE_NHAP_XUAT WHERE NGAY BETWEEN @STARTTIME AND @LASTTIME) AS NX,
			(SELECT MANX, MAVT, SOLUONG, DONGIA, THANHTIEN FROM @TABLE_CT_NHAP_XUAT) AS CT_NX,
			(SELECT MAVT, TENVT FROM dbo.VATTU) AS VT
		WHERE NX.MANX = CT_NX.MANX AND CT_NX.MAVT = VT.MAVT
		GROUP BY NX.THANG, VT.TENVT, NX.LOAI
	END
END