CREATE PROC [dbo].[sp_PhieuNvLapTrongNamTheoLoai ]
 @MANV int, @LOAI CHAR , @NAM INT
 AS
   SELECT PS.PHIEU ,  NGAY, TENVT , SOLUONG , DONGIA ,
    TRIGIA = SOLUONG * DONGIA 
   FROM PHATSINH PS , CT_PHATSINH CT, VATTU VT
   WHERE YEAR (NGAY)  = @NAM AND LOAI = @LOAI AND MANV  = @MANV  
       AND PS.PHIEU = CT.PHIEU AND CT.MAVT =VT.MAVT 
   ORDER BY NGAY , PS.PHIEU
