CREATE PROC [dbo].[SP_TongHop_NhapXuat]
	@ROLE VARCHAR(50),
	@STARTTIME DATE,
	@LASTTIME DATE
AS
BEGIN
	DECLARE @TONG_NHAP FLOAT
	DECLARE @TONG_XUAT FLOAT
	DECLARE @TABLE_TH_NHAP TABLE (NGAY DATE, NHAP FLOAT, TYLE_N FLOAT)
	DECLARE @TABLE_TH_XUAT TABLE (NGAY DATE, XUAT FLOAT, TYLE_X FLOAT)
	DECLARE @TABLE_TH_NHAPXUAT TABLE (NGAY DATE, NHAP FLOAT, TYLE_N FLOAT, XUAT FLOAT, TYLE_X FLOAT)
	IF (@ROLE = 'CHINHANH')
	BEGIN
		BEGIN
			SELECT @TONG_NHAP = SUM(SOLUONG * DONGIA) FROM dbo.PHIEUNHAP ,dbo.CTPN WHERE PHIEUNHAP.MAPN = CTPN.MAPN AND NGAY BETWEEN @STARTTIME AND @LASTTIME
			SELECT @TONG_XUAT = SUM(SOLUONG * DONGIA) FROM dbo.PHIEUXUAT, dbo.CTPX WHERE PHIEUXUAT.MAPX = CTPX.MAPX AND NGAY BETWEEN @STARTTIME AND @LASTTIME
			BEGIN --Chi co nhap
				INSERT @TABLE_TH_NHAP( NGAY, NHAP, TYLE_N )
				SELECT NGAY, SUM(SOLUONG * DONGIA) , ROUND(SUM(SOLUONG * DONGIA) / @TONG_NHAP, 2)  FROM dbo.PHIEUNHAP, dbo.CTPN WHERE PHIEUNHAP.MAPN = CTPN.MAPN AND NGAY BETWEEN @STARTTIME AND @LASTTIME
				GROUP BY NGAY
			END
			BEGIN -- Chi co Xuat
				INSERT @TABLE_TH_XUAT ( NGAY, XUAT, TYLE_X )			
				SELECT NGAY, SUM(SOLUONG * DONGIA) , ROUND(SUM(SOLUONG * DONGIA) / @TONG_XUAT, 2)  FROM dbo.PHIEUXUAT, dbo.CTPX WHERE PHIEUXUAT.MAPX = CTPX.MAPX AND NGAY BETWEEN @STARTTIME AND @LASTTIME
				GROUP BY NGAY
			END
			BEGIN -- nhap va xuat
				INSERT @TABLE_TH_NHAPXUAT ( NGAY, NHAP, TYLE_N, XUAT, TYLE_X )
				SELECT N.NGAY, N.NHAP, N.TYLE_N, X.XUAT, X.TYLE_X
				FROM (SELECT NGAY, NHAP, TYLE_N FROM @TABLE_TH_NHAP) AS N, (SELECT NGAY, XUAT, TYLE_X FROM @TABLE_TH_XUAT) AS X
				WHERE N.NGAY = x.NGAY
			END
		END 
	END
	IF (@ROLE = 'CONGTY')
	BEGIN
		DECLARE @TABLE_TH_NHAP_CN TABLE (NGAY DATE, NHAP FLOAT, TYLE_N FLOAT)
		DECLARE @TABLE_TH_XUAT_CN TABLE (NGAY DATE, XUAT FLOAT, TYLE_X FLOAT)
		BEGIN
			--Tong nhap xuat 2 chi nhanh
			SET @TONG_NHAP = (SELECT SUM(SOLUONG * DONGIA) FROM dbo.PHIEUNHAP ,dbo.CTPN WHERE PHIEUNHAP.MAPN = CTPN.MAPN AND NGAY BETWEEN @STARTTIME AND @LASTTIME) + 
			(SELECT SUM(SOLUONG * DONGIA) FROM LINK1.QLVT.dbo.PHIEUNHAP, LINK1.QLVT.dbo.CTPN WHERE PHIEUNHAP.MAPN = CTPN.MAPN AND NGAY BETWEEN @STARTTIME AND @LASTTIME)
			SET @TONG_XUAT = (SELECT SUM(SOLUONG * DONGIA) FROM dbo.PHIEUXUAT ,dbo.CTPX WHERE PHIEUXUAT.MAPX = CTPX.MAPX AND NGAY BETWEEN @STARTTIME AND @LASTTIME) + 
			(SELECT SUM(SOLUONG * DONGIA) FROM LINK1.QLVT.dbo.PHIEUXUAT, LINK1.QLVT.dbo.CTPX WHERE PHIEUXUAT.MAPX = CTPX.MAPX AND NGAY BETWEEN @STARTTIME AND @LASTTIME)
			-- Chi nhap/nhap_cn
			INSERT @TABLE_TH_NHAP( NGAY, NHAP, TYLE_N )
			SELECT NGAY, SUM(SOLUONG * DONGIA) , ROUND(SUM(SOLUONG * DONGIA) / @TONG_NHAP, 2)  FROM dbo.PHIEUNHAP, dbo.CTPN WHERE PHIEUNHAP.MAPN = CTPN.MAPN AND NGAY BETWEEN @STARTTIME AND @LASTTIME
			GROUP BY NGAY
			INSERT @TABLE_TH_NHAP_CN ( NGAY, NHAP, TYLE_N )
			SELECT NGAY, SUM(SOLUONG * DONGIA) , ROUND(SUM(SOLUONG * DONGIA) / @TONG_NHAP, 2)  FROM LINK1.QLVT.dbo.PHIEUNHAP, LINK1.QLVT.dbo.CTPN WHERE PHIEUNHAP.MAPN = CTPN.MAPN AND NGAY BETWEEN @STARTTIME AND @LASTTIME
			GROUP BY NGAY
			-- Chi xuat/xuat_cn
			INSERT @TABLE_TH_XUAT ( NGAY, XUAT, TYLE_X )			
			SELECT NGAY, SUM(SOLUONG * DONGIA) , ROUND(SUM(SOLUONG * DONGIA) / @TONG_XUAT, 2)  FROM dbo.PHIEUXUAT, dbo.CTPX WHERE PHIEUXUAT.MAPX = CTPX.MAPX AND NGAY BETWEEN @STARTTIME AND @LASTTIME
			GROUP BY NGAY
			INSERT @TABLE_TH_XUAT_CN ( NGAY, XUAT, TYLE_X )	     	
			SELECT NGAY, SUM(SOLUONG * DONGIA) , ROUND(SUM(SOLUONG * DONGIA) / @TONG_XUAT, 2)  FROM LINK1.QLVT.dbo.PHIEUXUAT, LINK1.QLVT.dbo.CTPX WHERE PHIEUXUAT.MAPX = CTPX.MAPX AND NGAY BETWEEN @STARTTIME AND @LASTTIME
			GROUP BY NGAY
			BEGIN --Chi co nhap ca 2 chi nhanh
				UPDATE @TABLE_TH_NHAP SET 
				NGAY =  [@TABLE_TH_NHAP].NGAY, NHAP = ([@TABLE_TH_NHAP].NHAP + [@TABLE_TH_NHAP_CN].NHAP), TYLE_N = ([@TABLE_TH_NHAP].TYLE_N + [@TABLE_TH_NHAP_CN].TYLE_N)
				FROM @TABLE_TH_NHAP, @TABLE_TH_NHAP_CN WHERE [@TABLE_TH_NHAP].NGAY = [@TABLE_TH_NHAP_CN].NGAY
			END
			BEGIN -- Chi co Xuat ca 2 chi nhanh
				UPDATE @TABLE_TH_XUAT	
				SET NGAY =  [@TABLE_TH_XUAT].NGAY, XUAT = ([@TABLE_TH_XUAT].XUAT + [@TABLE_TH_XUAT_CN].XUAT), TYLE_X = ([@TABLE_TH_XUAT].TYLE_X + [@TABLE_TH_XUAT_CN].TYLE_X)
				FROM @TABLE_TH_XUAT, @TABLE_TH_XUAT_CN WHERE [@TABLE_TH_XUAT].NGAY = [@TABLE_TH_XUAT_CN].NGAY
			END
			BEGIN -- nhap va xuat
				INSERT @TABLE_TH_NHAPXUAT ( NGAY, NHAP, TYLE_N, XUAT, TYLE_X )
				SELECT N.NGAY, N.NHAP, N.TYLE_N, X.XUAT, X.TYLE_X
				FROM (SELECT NGAY, NHAP, TYLE_N FROM @TABLE_TH_NHAP) AS N, (SELECT NGAY, XUAT, TYLE_X FROM @TABLE_TH_XUAT) AS X
				WHERE N.NGAY = x.NGAY
			END
		END 
	END 
	SELECT * FROM @TABLE_TH_NHAPXUAT
END 