CREATE PROCEDURE [dbo].[SP_UndoSuaKho] @MAKHO nchar(6),
	@TENKHO nvarchar(30),
	@DIACHI nvarchar(100)
AS
BEGIN
	UPDATE KHO
	SET KHO.TENKHO = @TENKHO, KHO.DIACHI = @DIACHI
	WHERE (KHO.MAKHO = @MAKHO);
END
